#!/bin/bash
#
# Installs gRPC the core in an existing Homebrew or Linuxbrew installation.
#
# prerequisites: Homebrew(Mac), Linuxbrew(Linux) is installed.
#
# Usage: curl -fsSL https://raw.githubusercontent.com/tbetbetbe/homebrew-grpc/master/scripts/install | bash -

__grpc_check_for_brew() {
    which 'brew' >> /dev/null || {
        if [ "$(uname)" == "Darwin" ]; then
            echo "Cannot find the brew command - please ensure you have installed Homebrew (http://brew.sh)";
        elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
            echo "Cannot find the brew command - please ensure you have installed Linuxbrew (https://github.com/Homebrew/linuxbrew#installation)";
        else
            echo "Your system is neither a Mac nor Linux, so gRPC is not currently supported";
        fi
        return 1;
    }
}


__grpc_brew_install() {
    local pkg=${!#}
    if brew list -1 | grep -q "^${pkg}\$"; then
        echo "$pkg is already installed"
        return;
    else
        brew install $@
    fi
}

__grpc_install_with_brew() {
    # Explicitly install OpenSSL.
    if [ "$(uname)" != "Darwin" ]; then
        # there may be unresolved dependency issues installing openssl using linuxbrew on macs.
        __grpc_brew_install pkg-config
        __grpc_brew_install openssl
    else
        __grpc_brew_install openssl
    fi

    # On linux, explicitly install  unzip if it's not present, it's a protobuf dependency
    # TODO: add this to the official homebrew formula
    if [ "$(uname)" != "Darwin" ]; then
        which 'unzip' >> /dev/null || {
            brew tap homebrew/dupes
            __grpc_brew_install unzip
        }
    fi

    # Explicitly install protobuf.
    #
    # We need the alpha version of protobuf, that's currently packaged a devel package, and
    # for new we're installing the head version of gRPC
    # install it explicitly.
    __grpc_brew_install --devel protobuf

    # Install gRPC
    brew tap tbetbetbe/grpc
    __grpc_brew_install --HEAD grpc
}

__grpc_install_ruby_pkg() {
    which 'ruby' >> /dev/null || {
        echo "Could not detect ruby; is ruby installed properly? Please check $PATH and maybe install and try again";
        return 1;
    }
    if [ "$(uname)" != "Darwin" ]; then
        # Linux brew; help gem find the grpc core.
        gem install grpc -- --with-grpc-dir=$HOME/.linuxbrew
    else
        gem install grpc
    fi
}

__grpc_install_nodejs_pkg() {
    which 'npm' >> /dev/null || {
        echo "Could not detect npm; is node installed properly? Please check $PATH and maybe install and try again";
        return 1;
    }
    if [ "$(uname)" != "Darwin" ]; then
        # Linux brew; help npm find the grpc core.
        CXXFLAGS=-I$HOME/.linuxbrew/include LDFLAGS=-L$HOME/.linuxbrew/lib npm install grpc
    else
        npm install grpc
    fi
}

# TODO: add __grpc_install_{php,python}_pkg

__grpc_install_pkgs() {
    for pkg in $@; do
        if [[ "$@" =~ "$pkg" ]]; then
            echo "installing grpc $pkg";
            local cmd="__grpc_install_${pkg}_pkg";
            $cmd;
        fi
    done
}

main() {
    __grpc_check_for_brew || exit 1;
    __grpc_install_with_brew;
    __grpc_install_pkgs "$@";
}

main "$@"
