#!/bin/bash
#
# Installs gRPC in a Homebrew or Linuxbrew installation.
#
# Prerequisites: Homebrew(Mac) / Linuxbrew(Linux) is installed.
#  - to install homebrew: see http://brew.sh
#  - to install linuxbrew: https://github.com/Homebrew/linuxbrew#installation
#
# Usage:
#
# Install grpc core:
#   curl -fsSL https://goo.gl/getgrpc | bash -
#
# Install grpc ruby:
#   curl -fsSL https://goo.gl/getgrpc | bash -s ruby
#
# Install grpc nodejs:
#   curl -fsSL https://goo.gl/getgrpc | bash -s nodejs
#
# Install grpc python:
#   curl -fsSL https://goo.gl/getgrpc | bash -s python

__grpc_check_for_brew() {
    which 'brew' >> /dev/null || {
        if [ "$(uname)" == "Darwin" ]; then
            echo "Cannot find the brew command - please ensure you have installed Homebrew (http://brew.sh)";
        elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
            echo "Cannot find the brew command - please ensure you have installed Linuxbrew (https://github.com/Homebrew/linuxbrew#installation)";
        else
            echo "Your system is neither a Mac nor Linux, so gRPC is not currently supported";
        fi
        return 1;
    }
}

__grpc_brew_install() {
    local pkg=${!#}
    if brew list -1 | grep -q "^${pkg}\$"; then
        echo "$pkg is already installed"
        return;
    else
        brew install $@
    fi
}

__grpc_brew_root() {
    __grpc_check_for_brew || return 1;
    brew config | grep HOMEBREW_PREFIX | cut -f 2 -d' '
}

__grpc_install_with_brew() {
    # Explicitly install OpenSSL.
    if [ "$(uname)" != "Darwin" ]; then
        # there may be unresolved dependency issues installing openssl using linuxbrew on macs.
        __grpc_brew_install pkg-config
        __grpc_brew_install openssl
    else
        __grpc_brew_install openssl
    fi

    # On linux, explicitly install  unzip if it's not present, it's a protobuf dependency
    # TODO: add this to the official homebrew formula
    if [ "$(uname)" != "Darwin" ]; then
        which 'unzip' >> /dev/null || {
            brew tap homebrew/dupes
            __grpc_brew_install unzip
        }
    fi

    # Explicitly install protobuf.
    #
    # We need the alpha version of protobuf, that's currently packaged a devel package, and
    # for new we're installing the head version of gRPC
    # install it explicitly.
    __grpc_brew_install --devel protobuf

    # Install gRPC
    brew tap grpc/grpc
    __grpc_brew_install --HEAD grpc
}

__grpc_install_ruby_pkg() {
    which 'ruby' >> /dev/null || {
        echo "Could not detect ruby; is ruby installed properly? Please check $PATH and maybe install and try again";
        return 1;
    }
    # support custom install locations: that's the default for linuxbrew and may
    # be used in homebrew install as well
    local brew_root=$(__grpc_brew_root)
    gem install grpc -- --with-grpc-dir=$brew_root
}

__grpc_install_nodejs_pkg() {
    which 'npm' >> /dev/null || {
        echo "Could not detect npm; is node installed properly? Please check $PATH and maybe install and try again";
        return 1;
    }
    # support custom install locations: that's the default for linuxbrew and may
    # be used in homebrew install as well
    local brew_root=$(__grpc_brew_root)
    CXXFLAGS=-I${brew_root}/include LDFLAGS=-L${brew_root}/lib npm install --global grpc
}

__grpc_install_python_pkg() {
    which 'pip' >> /dev/null || {
        echo "Could not detect pip; is it (and python) installed properly? Please check $PATH and maybe install and try again";
        return 1;
    }
    # support custom install locations, that's the default for linuxbrew and may
    # be used in homebrew install as well
    local brew_root=$(__grpc_brew_root)
    CFLAGS=-I${brew_root}/include LDFLAGS=-L${brew_root}/lib pip install grpcio
}

# TODO: add __grpc_install_php_pkg

__grpc_install_pkgs() {
    local known_pkgs="ruby python nodejs"
    for pkg in $@; do
        if [[ "$known_pkgs" =~ "$pkg" ]]; then
            echo "installing grpc $pkg";
            local cmd="__grpc_install_${pkg}_pkg";
            $cmd;
        else
            echo "did not install package for ${pkg}; this what not known"
        fi
    done
}

main() {
    __grpc_check_for_brew || exit 1;
    __grpc_install_with_brew;
    __grpc_install_pkgs "$@";
}

main "$@"
